name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup HUGO
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.140.1'
    - name: Render
      working-directory: 'site'
      run: hugo
    - name: Upload Content
      run: |
        aws s3 sync site/public s3://javaalmanac.io/ --delete --no-progress
        aws cloudfront create-invalidation --distribution-id ECI1PGYSTNAWG --paths "/*"
      
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'


  publish-data:
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.DATA_API_BUCKET }}
      DISTRIBUTION: ${{ secrets.DATA_API_DISTRIBUTION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Build and Run with Maven
      run: |
        cd dataapi
        mvn -B clean compile exec:java --no-transfer-progress
