name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup HUGO
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.136.5'
    - name: Render
      working-directory: 'site'
      run: hugo
    - name: Deploy
      working-directory: 'site'
      run: hugo deploy --invalidateCDN
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'


  publish-data:
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.DATA_API_BUCKET }}
      DISTRIBUTION: ${{ secrets.DATA_API_DISTRIBUTION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Build and Run with Maven
      run: |
        cd dataapi
        mvn -B clean compile exec:java --no-transfer-progress
